config/routes.rb
Consigliere::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "signin", :sign_out => "signout" }

  root to: "articles#index"

  resources :articles
  get "/drafts", to: "articles#drafts"
  post "/articles/:id/publish", to: "articles#publish"
  get "/feed", to: "articles#feed", defaults: { format: 'rss' }

  get "/about", to: "pages#about"
  get "/portfolio", to: "pages#portfolio"
  get "/contacts", to: "pages#contacts"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  	user ||= User.new
    if user.role.name == "Padrone"
        can :manage, :all
    else
    	can :read, Article
      can :feed, Article
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :title, :preview, :body, :keywords, :description
	belongs_to :user

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [[:id, :title]]
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '900>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 4.megabytes
  validates_attachment_presence :data
  do_not_validate_attachment_file_type :data

  def url_content
    url(:content)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	has_many :articles

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	before_filter :configure_permitted_parameters, if: :devise_controller?

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_url, :alert => exception.message
	end

	before_filter do
		resource = controller_name.singularize.to_sym
		method = "#{resource}_params"
		params[resource] &&= send(method) if respond_to?(method, true)
	end

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy, :publish]
	before_filter :authenticate_user!, :except => [:index, :show, :feed]
  before_filter :disable_xss_protection
  load_and_authorize_resource

	# GET /articles
	def index
		@articles = Article.all.where.not(published_at: nil).order('published_at DESC').page(params[:page]).per(5)
	end

	def drafts
		if user_signed_in? && current_user.role.name == "Padrone"
			@articles = Article.all.where(published_at: nil).order('created_at DESC')
		else
			redirect_to root_path
		end
	end

  def feed
    @articles = Article.all.where.not(published_at: nil).order('published_at DESC').limit(10)
    render "articles/feed", layout: false
  end

	# GET /articles/1
	def show
	end

	# GET /articles/new
	def new
		@article = Article.new
	end

	# GET /articles/1/edit
	def edit
	end

	# POST /articles
	# POST /articles.json
	def create
		@article = Article.new(article_params)
		@article.user = current_user

		respond_to do |format|
			if @article.save
				# Create URL slug for article on creation
				@article.slug = nil
				@article.save

				format.html { redirect_to drafts_path, notice: 'Article was successfully created.' }
			else
				format.html { render action: 'new' }
			end
		end
	end

	# POST "/articles/1/publish"
	def publish
		if @article.published_at
			redirect_to root_path
			return
		end

		@article.published_at = DateTime.current
		respond_to do |format|
			if @article.save
				format.html { redirect_to root_path, notice: 'Article was successfully published.' }
			else
				format.html { render action: 'edit' }
			end
		end
	end

	# PATCH/PUT /articles/1
	# PATCH/PUT /articles/1.json
	def update
    # Force update slug
    @article.slug = nil

		respond_to do |format|
			if @article.update(article_params)
				format.html {
					if @article.published_at
						# Updated published article
						redirect_to @article, notice: 'Article was successfully updated.'
					else
						# Updated article in drafts
						redirect_to drafts_path, notice: 'Article was successfully updated.'
					end
				}
			else
				format.html { render action: 'edit' }
			end
		end
	end

	# DELETE /articles/1
	# DELETE /articles/1.json
	def destroy
		if @article.published_at
			# Deleted published article
			@article.destroy
			respond_to do |format|
				format.html { redirect_to articles_url }
			end
		else
			# Deleted article from drafts
			@article.destroy
			respond_to do |format|
				format.html { redirect_to drafts_path }
			end
		end
	end

		private
		# Use callbacks to share common setup or constraints between actions.
		def set_article
			@article = Article.friendly.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def article_params
			params.require(:article).permit(:title, :body, :preview, :description, :keywords)
    end

    def disable_xss_protection
      response.headers['X-XSS-Protection'] = "0"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def portfolio
  end

  def about
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.slim
- content_for :head do
	= javascript_include_tag "/assets/ckeditor/ckeditor"
	= javascript_include_tag "/assets/ckeditor/init"

= form_for(@article) do |f|
  - if @article.errors.any?
    #error_explanation
	  h2 #{pluralize(@article.errors.count, "error")} prohibited this article from being saved:
	  ul
	    - @article.errors.full_messages.each do |msg|
		  li = msg

  .field.form-group
    = f.label :title
    br
    = f.text_field :title, autocomplete: :off, class: "form-control"

  .field.form-group
    = f.label :preview
    br
    = f.text_area :preview, class: "ckeditor"

  .field.form-group
    = f.label :article
    br
    = f.text_area :body, class: "ckeditor"

  .field.form-group
    = f.label :description
    br
    = f.text_field :description, class: "form-control"

  .field.form-group
    = f.label :keywords
    br
    = f.text_field :keywords, class: "form-control"

  .actions
    = f.submit class: "btn btn-primary"
    = link_to 'Back', articles_path, class: "btn btn-default"

app/views/articles/_social.slim
ul.soc.center
  li
    a.soc-twitter href="https://twitter.com/intent/tweet?url=#{CGI.escape(request.original_url)}" target="_blank"
  li
    a.soc-facebook href="https://www.facebook.com/sharer.php?u=#{CGI.escape(request.original_url)}" target="_blank"
  li
    a.soc-google href="https://plus.google.com/share?url=#{CGI.escape(request.original_url)}" target="_blank"
  li
    a.soc-linkedin href="https://www.linkedin.com/shareArticle?url=#{CGI.escape(request.original_url)}&title=#{URI.encode(article.title) unless article.title.nil?}&summary=#{URI.encode(article.description) unless article.description.nil?}" target="_blank"
  li
    a.soc-vkontakte href="https://vk.com/share.php?url=#{CGI.escape(request.original_url)}" target="_blank"

app/views/articles/drafts.slim
- set_meta_tags title: "All Articles",
                description: "List of all articles on this blog",
                keywords: "iOS, Ruby, Rails, Swift, Objective C, developer, development, Apple, iPhone, iPad, iPod touch, freelance, freelancer, oDesk, elance"

.myrow
  .column.column-800

    - if can? :create, @article
      = link_to 'New Article', new_article_path, class: "btn btn-primary"
      br

    - @articles.each do |article|
      .article
        div
          h1 = link_to article.title, article

        .content
          = article.preview.html_safe

        .buttons
          - if can? :publish, article
            = link_to "Publish", "/articles/#{article.id}/publish", method: :post, class: "btn btn-success"

          = link_to "Read", article, class: "btn btn-primary"

          - if can? :update, article
            = link_to "Edit", edit_article_path(article), class: "btn btn-default"

          - if can? :destroy, article
            = link_to "Delete", article, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

app/views/articles/edit.slim
- set_meta_tags title: "Edit Article - #{@article.title}",
                description: "Edit article page",
                keywords: "edit, article, page, iOS, Ruby, Rails, Swift, Objective C, developer, development, Apple, iPhone, iPad, iPod touch, freelance, freelancer, oDesk, elance",
                noindex: true

.myrow
  .column.column-800
    = render 'form'

app/views/articles/index.slim
- set_meta_tags title: "All Articles",
                description: "List of all articles on this blog",
                keywords: "iOS, Ruby, Rails, Swift, Objective C, developer, development, Apple, iPhone, iPad, iPod touch, freelance, freelancer, oDesk, elance"

.myrow
  .column.column-800
    .center
      = paginate @articles, theme: "twitter-bootstrap-3"

    - @articles.each do |article|
      .article
        div
          h1.center = link_to article.title, article

        .content
          = article.preview.html_safe

        .buttons.center
          = link_to "Read", article, class: "btn btn-primary"

          - if can? :update, article
            = link_to "Edit", edit_article_path(article), class: "btn btn-default"

          - if can? :destroy, article
            = link_to "Delete", article, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"

    .center
      = paginate @articles, theme: "twitter-bootstrap-3"

app/views/articles/new.slim
- set_meta_tags title: "New Article",
                description: "New article page",
                keywords: "new, article, page, iOS, Ruby, Rails, Swift, Objective C, developer, development, Apple, iPhone, iPad, iPod touch, freelance, freelancer, oDesk, elance",
                noindex: true

.myrow
  .column.column-800
    h1 New Article
    = render 'form'

app/views/articles/show.slim
- set_meta_tags title: "#{@article.title}",
                description: "#{@article.description}",
                keywords: "#{@article.keywords}"

.myrow
  .column.column-800
    div
	  h1.center = @article.title

    .content
	  = @article.body.html_safe

    hr

    - if @article.published_at
      p.center
        em
          | Posted by #{@article.user.username} on #{@article.published_at.strftime("%B %d, %Y")}
          br
          | last update #{@article.updated_at.strftime("%B %d, %Y")}
          br
      hr

    = render "articles/social", article: @article
    hr

    .buttons.center
      - if can? :publish, @article
        - if @article.published_at.nil?
          = link_to "Publish", "/articles/#{@article.id}/publish", method: :post, class: "btn btn-success"

	  - if can? :update, @article
	    = link_to 'Edit', edit_article_path(@article), class: "btn btn-primary"

      - if can? :destroy, @article
        = link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

      - if @article.published_at
	    = link_to 'Back', articles_path, class: "btn btn-default"
	  - else
        = link_to 'Back', drafts_path, class: "btn btn-default"

- if Rails.env.production?
  .myrow
    .column.column-800
      #disqus_thread

      javascript:
        var disqus_shortname = "myrailsblog",
            disqus_identifier = "#{@article.id}",
            disqus_title = "#{@article.title}",
            disqus_url = "#{request.original_url}",

        dsq = document.createElement('script');
        dsq.type = 'text/javascript';
        dsq.async = true;
        dsq.src = "//" + disqus_shortname + ".disqus.com/embed.js";
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);

      noscript
        ' Please enable JavaScript to view the
        a href="http://disqus.com/?ref_noscript" comments powered by Disqus.
      a.dsq-brlink href="http://disqus.com"
        ' comments powered by
        span.logo-disqus Disqus

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= auto_discovery_link_tag(:rss, "http://0.0.0.0:3000/feed") %>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "/assets/highlight.pack.js" %>
  <script>
      hljs.initHighlightingOnLoad();

      $(document).ready(function() {
          $(".owl-carousel-1").owlCarousel({
              items: 1,
              itemsDesktop: false,
              itemsDesktopSmall: false,
              itemsTablet: false,
              itemsTabletSmall: false,
              itemsMobile: false,
              itemsCustom: false
          });
          $(".owl-carousel-2").owlCarousel({
              items: 2,
              itemsDesktop: false,
              itemsDesktopSmall: false,
              itemsTablet: false,
              itemsTabletSmall: false,
              itemsMobile: false,
              itemsCustom: [[400, 1], [640, 2]]
          });
          $(".owl-carousel-3").owlCarousel({
              items: 3,
              itemsDesktop: false,
              itemsDesktopSmall: false,
              itemsTablet: false,
              itemsTabletSmall: false,
              itemsMobile: false,
              itemsCustom: [[400, 1], [640, 2], [800, 3]]
          });
      });
  </script>

  <%= yield :head %>

  <%= display_meta_tags %>

  <link href="/favicon.ico" rel="shortcut icon"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body>

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('iOS on Rails', root_path, :class => "navbar-brand") %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'articles' && (params[:action] == 'index' || params[:action] == 'show') %>">
          <%= link_to('Blog', articles_path) %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'about' %>">
          <a href="/about">About</a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'portfolio' %>">
          <a href="/portfolio">Portfolio</a>
        </li>
        <li class="<%= 'active' if params[:controller] == 'pages' && params[:action] == 'contacts' %>">
          <a href="/contacts">Contacts</a>
        </li>
        <% if user_signed_in? && current_user.role.name == "Padrone" %>
            <li class="<%= 'active' if params[:controller] == 'articles' && params[:action] == 'drafts' %>">
              <a href="/drafts">Drafts</a>
            </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('', feed_path, { class: "fa fa-rss" }) %></li>
        <% if user_signed_in? %>
            <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
            <li class='<%= (params[:controller]=='devise/sessions')&(params[:action]=='new') ? 'active' : '' %>'><%= link_to('Sign In', new_user_session_path) %></li>
            <li class='<%= (params[:controller]=='devise/registrations')&(params[:action]=='new') ? 'active' : '' %>'><%= link_to('Register', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% if notice %>
    <div class="myrow">
      <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-warning alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <p id="notice"><%= notice %></p>
        </div>
      </div>
    </div>
<% end %>

<%= yield %>

<div style="clear:both;"></div>

<% if Rails.env.production? %>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-46802250-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
<% end %>

</body>
</html>

app/views/pages/about.slim
- set_meta_tags title: "About",
                description: "About me page",
                keywords: "about, iOS, Ruby, Rails, Swift, Objective C, developer, development, Apple, iPhone, iPad, iPod touch, freelance, freelancer, oDesk, elance"

.column.column-800

  h1 Welcome to my blog

  img.image-text-wrap src="http://skliarov.com/ckeditor_assets/pictures/77/content_0270.jpg"

  p My name is Maksym Skliarov. I'm iOS and Ruby on Rails developer from Ukraine.
  p I'm passionate about what I do and I always deliver the best user experience in mobile apps and websites I develop.
  p
    'During the last couple of month I've been freelancing at oDesk. Cool place to work! Here is my
    a href="https://www.odesk.com/users/%7E0155b1b691e97e3a9b" target="_blank" profile
    '  there. I'm in top 10% of oDesk freelancers in iOS and Ruby on Rails development, HTML5, CSS and Software Testing with overall 5.0 star client's feedback.
  p I have a small team that consists of designer, 2 Android developers and 2 QA engineers that work with me on per project basis.
  p Agile methodology helped me a lot while working in small teams with other developers and designers.
  p
    'If you have an awesome iOS, Android, Ruby on Rails project (or all of them), feel free to
    a href="/contacts" contact me
    '.

  br

  p P.S. Except my work I like good music (blues, classic rock), playing guitar, longboarding, skiing, skating, swimming, enjoying life.

app/views/pages/contacts.slim
- set_meta_tags title: "Contacts",
                description: "My contacts",
                keywords: "contacts, iOS, Ruby, Rails, Swift, Objective C, developer, development, Apple, iPhone, iPad, iPod touch, freelance, freelancer, oDesk, elance"

.column.column-800
  h1 You can find me here
  a.contacts href="https://www.linkedin.com/in/maksymskliarov" target="_blank"
    .fa.fa-linkedin-square.fa-5x
  a.contacts href="https://www.facebook.com/maksym.skliarov" target="_blank"
    .fa.fa-facebook-square.fa-5x
  a.contacts href="https://twitter.com/iOSonRails" target="_blank"
    .fa.fa-twitter-square.fa-5x
  a.contacts href="https://plus.google.com/+MaksymSkliarov1" target="_blank"
    .fa.fa-google-plus-square.fa-5x
  a.contacts href="https://www.youtube.com/channel/UCIGwNBVhXzvZNxaAzdRLdwQ" target="_blank"
    .fa.fa-youtube-square.fa-5x
  a.contacts href="skype:maksym.skliarov?chat"
    .fa.fa-skype.fa-5x
  a.contacts href="https://github.com/skliarov" target="_blank"
    .fa.fa-github-square.fa-5x
  a.contacts href="https://bitbucket.org/skliarov" target="_blank"
    .fa.fa-bitbucket-square.fa-5x

  br
  br

  p
    'My oDesk
    a href="https://www.odesk.com/users/%7E0155b1b691e97e3a9b" target="_blank" profile
    '.

  p
    'Also you can contact me via
    a href="mailto:maksym.skliarov@gmail.com" email
    '.